import_historical_data:
  name: Import historical energy data
  description: "Backfill energy usage statistics from iSolarCloud API. (Note: This can take a while if you select a long date interval.)"
  fields:
    start:
      name: Start time
      description: Start of the time period to import statistics for.
      required: true
      selector:
        datetime:
    end:
      name: End time
      description: End of the time period to import statistics for.
      required: true
      selector:
        datetime:
    delete:
      name: Delete existing data
      description: Delete existing data for the selected time period before importing new data.
      required: false
      selector:
        boolean:
    plant:
      name: Plant
      description: The plant to import data for. (Needed if you have multiple plants.)
      required: false
      selector:
        text:
list_data_points:
  name: List data points
  description: "List all available data points from iSolarCloud."
  fields:
    measure_points:
      name: Measure points
      description: List of measure point codes to query (optional).
      required: false
      selector:
        text:
          multiple: true
    plant:
      name: Plant
      description: The plant to get data for. (Needed if you have multiple plants.)
      required: false
      selector:
        text:
